Section "InputClass"
	Identifier "Avago Technologies mouse quirks (LP: #746639)"
	MatchIsPointer "on"
	MatchDevicePath "/dev/input/event*"
	Driver "evdev"
	MatchUSBID "192f:0416"
	Option "Emulate3Buttons" "True"
	Option "Emulate3Timeout" "50"
EndSection
